/* eslint-disable */

const airbnb = [
  {
    PlaceId: 'JP',
    PlaceName: '일본',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: '',
    IataCode: '',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '',
    CityNameEn: '',
    GeoId: '29475330',
    GeoContainerId: '29475330',
    Location: '37.3132725967,137.6721240928',
    ResultingPhrase: '일본',
    Highlighting: [[0, 2]],
  },
  {
    PlaceId: 'TYOA',
    PlaceName: '도쿄',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: 'TYOA',
    IataCode: 'TYO',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '도쿄',
    CityNameEn: '',
    GeoId: '27542089',
    GeoContainerId: '27542089',
    Location: '35.6889504799,139.7389466317',
    ResultingPhrase: '도쿄|도쿄 도|일본',
    Highlighting: [[8, 10]],
  },
  {
    PlaceId: 'NRT',
    PlaceName: '도쿄 나리타',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: 'TYOA',
    IataCode: '',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '도쿄',
    CityNameEn: '',
    GeoId: '128668889',
    GeoContainerId: '27542089',
    Location: '35.763889,140.391111',
    ResultingPhrase: '도쿄 나리타 (NRT), 도쿄|도쿄 도|일본',
    Highlighting: [[22, 24]],
  },
  {
    PlaceId: 'HND',
    PlaceName: '도쿄 하네다',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: 'TYOA',
    IataCode: '',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '도쿄',
    CityNameEn: '',
    GeoId: '128667143',
    GeoContainerId: '27542089',
    Location: '35.553611,139.765833',
    ResultingPhrase: '도쿄 하네다 (HND), 도쿄|도쿄 도|일본',
    Highlighting: [[22, 24]],
  },
  {
    PlaceId: 'OSAA',
    PlaceName: '오사카',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: 'OSAA',
    IataCode: 'OSA',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '오사카',
    CityNameEn: '',
    GeoId: '27542908',
    GeoContainerId: '27542908',
    Location: '34.6937458271,135.5021816223',
    ResultingPhrase: '오사카|오사카 부|일본',
    Highlighting: [[10, 12]],
  },
  {
    PlaceId: 'KIX',
    PlaceName: '오사카칸사이인터내셔널',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: 'OSAA',
    IataCode: '',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '오사카',
    CityNameEn: '',
    GeoId: '128667802',
    GeoContainerId: '27542908',
    Location: '34.423889,135.246944',
    ResultingPhrase: '오사카칸사이인터내셔널 (KIX), 오사카|오사카 부|일본',
    Highlighting: [[29, 31]],
  },
  {
    PlaceId: 'ITM',
    PlaceName: '오사카이타미',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: 'OSAA',
    IataCode: '',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '오사카',
    CityNameEn: '',
    GeoId: '104120225',
    GeoContainerId: '27542908',
    Location: '34.781667,135.441667',
    ResultingPhrase: '오사카이타미 (ITM), 오사카|오사카 부|일본',
    Highlighting: [[24, 26]],
  },
  {
    PlaceId: 'FUK',
    PlaceName: '후쿠오카',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: 'JFUK',
    IataCode: '',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '후쿠오카',
    CityNameEn: '',
    GeoId: '128667957',
    GeoContainerId: '27541740',
    Location: '33.582222,130.453333',
    ResultingPhrase: '후쿠오카 (FUK), 후쿠오카|Fukuoka-shi|후쿠오카 현|일본',
    Highlighting: [[36, 38]],
  },
  {
    PlaceId: 'OKA',
    PlaceName: '오키나와나하',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: 'JOKA',
    IataCode: '',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '오키나와',
    CityNameEn: '',
    GeoId: '128668904',
    GeoContainerId: '27540768',
    Location: '26.2,127.65',
    ResultingPhrase: '오키나와나하 (OKA), 오키나와|Okinawa-shi|오키나와 현|일본',
    Highlighting: [[38, 40]],
  },
  {
    PlaceId: 'JNGO',
    PlaceName: '나고야',
    LocalizedPlaceName: '',
    CountryId: 'JP',
    CityId: 'JNGO',
    IataCode: 'NGO',
    CountryName: '일본',
    PlaceNameEn: '',
    RegionId: '',
    CityName: '나고야',
    CityNameEn: '',
    GeoId: '27545106',
    GeoContainerId: '27545106',
    Location: '35.1814771633,136.906408681',
    ResultingPhrase: '나고야|아이치 현|일본',
    Highlighting: [[10, 12]],
  },
];

const a = {
  PlaceId: 'JP',
  PlaceName: '일본',
  LocalizedPlaceName: '',
  CountryId: 'JP',
  CityId: '',
  IataCode: '',
  CountryName: '일본',
  PlaceNameEn: '',
  RegionId: '',
  CityName: '',
  CityNameEn: '',
  GeoId: '29475330',
  GeoContainerId: '29475330',
  Location: '37.3132725967,137.6721240928',
  ResultingPhrase: '일본',
  Highlighting: [[0, 2]],
};

const d = [];

console.log(a.ResultingPhrase.replace(/(.{0})/, '<b>'));

for (let i = 0; i < a.ResultingPhrase.length; i++) {
  if (i === a.Highlighting[0][0]) {
    d.push(a.ResultingPhrase.replace(/(.{0})/, '<b>'));
  } else if (i === a.Highlighting[0][1] - 1) {
    d.push(a.ResultingPhrase.replace(/(.{2})/, '</b>'));
  }
}
console.log(d);
